## fichier à élaborer des variables a changer des ports a rediriger , pas encore fini sera fait à la fin du projet.
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./backend/:/var/www/html
    depends_on:
      - mysql
    networks:
      - backend

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./backend/:/var/www/html
    depends_on:
      - php
    networks:
      - backend
      - frontend

  node:
    build:
      context: ./frontend/
      dockerfile: ../docker/node/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - ./frontend/:/app
    ports:
      - "${VITE_HOST_PORT}:5173"
    networks:
      - frontend

  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  mongodb:
    image: mongo:${MONGO_VERSION}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  mysql_data:
  mongo_data:

networks:
  backend:
  frontend:
