version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file:
      - .env.dev
    volumes:
        - mysql_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3307:3306"
    container_name: my-mysql-container

  mongo:
    build:
      context: .
      dockerfile: ./docker/mongo/Dockerfile
    volumes:
      - mongo_data:/data/db
    ports:
      - "28017:27017"
    networks:
      - backend
    container_name: my-mongo-container

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./backend/:/var/www/html
    depends_on:
      - php
    networks:
      - backend
      - frontend
    container_name: my-nginx-container

  php:
    build:
      context: .
      dockerfile:  ./docker/php/Dockerfile
    volumes:
      - ./backend/:/var/www/html

    networks:
      - backend
    container_name: my-php-container

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile.node
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - "${NODE_PORT:-3000}:3000"  
    networks:
      - frontend
    container_name: my-node-container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST:  mysql
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - backend
    container_name: my-phpmyadmin-container

networks:
  backend:
  frontend:

volumes:
  mysql_data:
    name: arcadia_db_data
  mongo_data:
    name : arcadia_mongo_data
  node_modules_data:
    name: arcadia_node_modules
