services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    env_file:
      - .env.dev
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "${MYSQL_PORT}:3306"
    container_name: my-mysql-container

  mongo:
    build:
      context: .
      dockerfile: ./docker/mongo/Dockerfile
      args:
        MONGO_VERSION: ${MONGO_VERSION}
    env_file:
      - .env.dev
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - backend
    container_name: my-mongo-container

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./backend/:/var/www/html
    depends_on:
      - php
    networks:
      - backend
      - frontend
    container_name: my-nginx-container

  php:
    build:
      context: .
      dockerfile:  ./docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.0-fpm-alpine}  
    environment:
        PHP_PORT: ${PHP_PORT:-9000}  # Valeur par défaut pour le port PHP_FPM
    volumes:
      - ./backend/:/var/www/html
    networks:
      - backend
    container_name: my-php-container
    env_file:
      - .env.dev

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile.node
      args:
        NODE_VERSION: ${NODE_VERSION:-16-alpine}   # Passer la version de Node.js au ytravers du fchier .env.dev.
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - "${NODE_PORT:-3000}:3000" 
      - "${VITE_PORT:-5173}:5173" 
    networks:
      - frontend
    container_name: my-node-container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env.dev
    environment:
      PMA_HOST:  mysql
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - backend
    container_name: my-phpmyadmin-container

networks:
  backend:
    name: arcadia_backend_network
  frontend:
    name: arcadia_frontend_network
volumes:
  mysql_data:
    name: arcadia_db_data
  mongo_data:
    name : arcadia_mongo_data
  node_modules_data:
    name: arcadia_node_modules
