FROM node:16-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier le package.json et le package-lock.json
COPY frontend/package*.json ./
# Installer les dépendances
RUN npm install

# Copier le reste du code source
COPY ./frontend/ .

# Exposer le port 3000
EXPOSE 3000

CMD ["npm", "run", "dev"]
